/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bergmann
 */
public class janela extends javax.swing.JFrame {

    static Jogo jogoFrogger = new Jogo();

    /**
     * Creates new form janela
     */
    public janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblJogador = new javax.swing.JLabel();
        btnStartGame = new javax.swing.JButton();
        lblCalcada1 = new javax.swing.JLabel();
        lblCalcada2 = new javax.swing.JLabel();
        lblAsfalto1 = new javax.swing.JLabel();
        lblAsfalto3 = new javax.swing.JLabel();
        lblAsfalto2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblTitulo.setText("Frogger");

        lblJogador.setText("Jogador");

        btnStartGame.setText("Start");
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });

        lblCalcada1.setText("Calcada1");

        lblCalcada2.setText("Calcada2");

        lblAsfalto1.setText("Asfalto1");

        lblAsfalto3.setText("Asfalto3");

        lblAsfalto2.setText("Asfalto2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCalcada2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCalcada1)
                                .addGap(18, 18, 18)
                                .addComponent(lblJogador))
                            .addComponent(lblAsfalto3)
                            .addComponent(lblAsfalto1)
                            .addComponent(lblAsfalto2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(btnStartGame)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCalcada2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAsfalto3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAsfalto2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAsfalto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCalcada1)
                    .addComponent(lblJogador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(btnStartGame)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed
        // TODO add your handling code here:
        jogoFrogger.setPodeiniciar(true);
    }//GEN-LAST:event_btnStartGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janela().setVisible(true);
            }
        });

        
        jogoFrogger.mostraMenu();
        
        // Setando os labels para os labels criados na classe Jogo.(Vinculando-os)
        jogoFrogger.setLblJogador(lblJogador);
        jogoFrogger.setCalcada1(lblCalcada1);
        jogoFrogger.setCalcada2(lblCalcada2);
        jogoFrogger.setAsfalto1(lblAsfalto1);
        jogoFrogger.setAsfalto2(lblAsfalto2);
        jogoFrogger.setAsfalto3(lblAsfalto3);
        
        // Esses comandos tornam o titulo Frogger e o botao Start invisiveis.
        lblTitulo.setVisible(false);
        btnStartGame.setVisible(false);

        jogoFrogger.iniciaJogo();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnStartGame;
    private static javax.swing.JLabel lblAsfalto1;
    private static javax.swing.JLabel lblAsfalto2;
    private static javax.swing.JLabel lblAsfalto3;
    private static javax.swing.JLabel lblCalcada1;
    private static javax.swing.JLabel lblCalcada2;
    private static javax.swing.JLabel lblJogador;
    public static javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
