
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Júlia
 */
public class MenuFimDeJogo extends javax.swing.JPanel {

    private final ImageIcon enterro;
    private Janela parent;
    
    /**
     * Creates new form MenuFimDeJogo
     * @throws java.io.IOException
     */
    public MenuFimDeJogo(Janela janela) throws IOException {
        initComponents();
        this.enterro = new ImageIcon(ImageIO.read(new File("imagens/enterro.png")).getScaledInstance(320, 190, Image.SCALE_SMOOTH));
    
        lblEnterro.setIcon(enterro);
        
        this.setParent(janela);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnterro = new javax.swing.JLabel();
        lblFimDeJogo = new javax.swing.JLabel();
        lblPontuacao = new javax.swing.JLabel();
        btnJogarNovamente = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        lblFimDeJogo.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblFimDeJogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFimDeJogo.setText("Fim de Jogo");

        lblPontuacao.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblPontuacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPontuacao.setText("Você fez XXXXX pontos!");

        btnJogarNovamente.setText("Jogar Novamente");
        btnJogarNovamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarNovamenteActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar ao Menu Inicial");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lblEnterro, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnJogarNovamente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFimDeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblEnterro, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFimDeJogo)
                .addGap(18, 18, 18)
                .addComponent(lblPontuacao)
                .addGap(37, 37, 37)
                .addComponent(btnJogarNovamente)
                .addGap(30, 30, 30)
                .addComponent(btnVoltar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setParent(Janela parent) {
        this.parent = parent;
    }
    
    private void btnJogarNovamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarNovamenteActionPerformed
        parent.novoJogo();
    }//GEN-LAST:event_btnJogarNovamenteActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        parent.mostraMenu();
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogarNovamente;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblEnterro;
    private javax.swing.JLabel lblFimDeJogo;
    private javax.swing.JLabel lblPontuacao;
    // End of variables declaration//GEN-END:variables
}
