
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Júlia
 */
public class PainelDeJogo extends javax.swing.JPanel {

    /**
     * Creates new form PainelDeJogo
     */
    public PainelDeJogo() {
        initComponents();
    }

    public JLabel getAsfalto1() {
        return asfalto1;
    }

    public JLabel getAsfalto2() {
        return asfalto2;
    }

    public JLabel getAsfalto3() {
        return asfalto3;
    }

    public JLabel getCalcada1() {
        return calcada1;
    }

    public JLabel getCalcada2() {
        return calcada2;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        calcada2 = new javax.swing.JLabel();
        asfalto3 = new javax.swing.JLabel();
        asfalto2 = new javax.swing.JLabel();
        asfalto1 = new javax.swing.JLabel();
        calcada1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        calcada2.setText("calcada2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(calcada2, gridBagConstraints);

        asfalto3.setText("asfalto3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(asfalto3, gridBagConstraints);

        asfalto2.setText("asfalto2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(asfalto2, gridBagConstraints);

        asfalto1.setText("asfalto1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(asfalto1, gridBagConstraints);

        calcada1.setText("calcada1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(calcada1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asfalto1;
    private javax.swing.JLabel asfalto2;
    private javax.swing.JLabel asfalto3;
    private javax.swing.JLabel calcada1;
    private javax.swing.JLabel calcada2;
    // End of variables declaration//GEN-END:variables
}
