
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Júlia
 */
public class Tutorial extends javax.swing.JPanel {
    
    private final ImageIcon sapo;
    private final ImageIcon carro;
    private final ImageIcon moto;
    private final ImageIcon caminhao;
    private final ImageIcon teclas;
    private final ImageIcon coracao;

    /**
     * Creates new form Tutorial
     * @throws java.io.IOException
     */
    public Tutorial() throws IOException {
        this.sapo = new ImageIcon(ImageIO.read(new File("imagens/sapoTras1.png")).getScaledInstance(100, 100, Image.SCALE_SMOOTH));
        this.carro = new ImageIcon(ImageIO.read(new File("imagens/carro.png")).getScaledInstance(100, 100, Image.SCALE_SMOOTH));
        this.moto = new ImageIcon(ImageIO.read(new File("imagens/moto.png")).getScaledInstance(100, 100, Image.SCALE_SMOOTH));
        this.caminhao = new ImageIcon(ImageIO.read(new File("imagens/caminhao.png")).getScaledInstance(100, 100, Image.SCALE_SMOOTH));
        this.teclas = new ImageIcon(ImageIO.read(new File("imagens/teclas.png")).getScaledInstance(100, 100, Image.SCALE_SMOOTH));
        this.coracao = new ImageIcon(ImageIO.read(new File("imagens/coracao.png")).getScaledInstance(100, 100, Image.SCALE_SMOOTH));
        
        initComponents();
        
        lblJogador.setIcon(sapo);
        lblCarro.setIcon(carro);
        lblMoto.setIcon(moto);
        lblCaminhao.setIcon(caminhao);
        lblTeclas.setIcon(teclas);
        lblCoracao.setIcon(coracao);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTeclas = new javax.swing.JLabel();
        lblCarro = new javax.swing.JLabel();
        lblMoto = new javax.swing.JLabel();
        lblCaminhao = new javax.swing.JLabel();
        lblJogador = new javax.swing.JLabel();
        lblCoracao = new javax.swing.JLabel();

        lblTeclas.setText("Teclas");
        lblTeclas.setPreferredSize(new java.awt.Dimension(100, 100));

        lblCarro.setText("carro");
        lblCarro.setMaximumSize(new java.awt.Dimension(200, 200));
        lblCarro.setPreferredSize(new java.awt.Dimension(100, 100));

        lblMoto.setText("moto");
        lblMoto.setMaximumSize(new java.awt.Dimension(200, 200));
        lblMoto.setPreferredSize(new java.awt.Dimension(100, 100));

        lblCaminhao.setText("caminhao");

        lblJogador.setText("sapo");
        lblJogador.setMaximumSize(new java.awt.Dimension(200, 200));
        lblJogador.setPreferredSize(new java.awt.Dimension(100, 100));

        lblCoracao.setText("coracao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCaminhao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(lblCoracao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTeclas, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(lblJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTeclas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCaminhao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCoracao, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCaminhao;
    private javax.swing.JLabel lblCarro;
    private javax.swing.JLabel lblCoracao;
    private javax.swing.JLabel lblJogador;
    private javax.swing.JLabel lblMoto;
    private javax.swing.JLabel lblTeclas;
    // End of variables declaration//GEN-END:variables
}
